### ISSUE TITLE
save computational time

### ISSUE THREAD

**Issue by willianmh** [akshaybahadur21/fashion-MNIST#1]
On [fashion_nn.py](https://github.com/akshaybahadur21/fashion-MNIST/blob/master/fashion_nn.py) you can compute the cost inside the conditon on line 143
```
if i % 100 == 0:
  cost = compute_cost(A2, Y, parameters)
  costs.append(cost)
  if print_cost:
    print("Cost after iteration for %i: %f" % (i, cost))
```

**Comment by akshaybahadur21** [comment]
@willianmh - Thanks.
Let me do the changes
